config/routes.rb
Rails.application.routes.draw do

  get  'login'  => 'sessions#new'
  post 'login'  => 'sessions#login'
  post 'logout' => 'sessions#logout'

  root 'home#index'

  get 'messages/:to_id' => 'messages#new'
  resources :messages
  resources :users
  get 'signup' => 'users#new'

  resources :punches
  get 'punches' => 'punches#index'

  resources :interests

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/punch.rb
class Punch < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true
  validates :user_punched, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :interests

  #valid formats
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true
  validates :email, presence: true, 
            uniqueness: {case_sensitive: false},
            format: { with:VALID_EMAIL_REGEX }
  #validates :birthday, presence: true
  validates :password, confirmation: true, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController

  before_action :find_user, only: [:new, :create]

  def new
    @interest = Interest.new
  end

  def create
    interest = Interest.new(interests_params)
    if interest.save!
      flash[:notice] = 'Interest saved with success'
      redirect_to @user
    else
      flash[:notice] = 'Something went wrong saving your interest'
      render :new
    end
  end

  def destroy
  end

  def edit
  end

  private

    def interests_params
      params.require(:interest).permit(:name, :user_id)
    end

    def find_user
      @user = current_user
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @user = current_user
    @messages_from_user = Message.where(from: @user.id)
    @messages_to_user = Message.where(to: @user.id)

    @all_messages = []

    @messages_from_user.each do |message|
      @all_messages << message
    end

    @messages_to_user.each do |message|
      @all_messages << message
    end

    @conversations = []
    @all_messages.each do |message|
      @conversations << message.from if message.from != @user.id
      @conversations << message.to if message.to != @user.id
    end

    @conversations.uniq!.map!(){ |id| User.find(id) }
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @user = current_user
    @to_user = User.find(params[:to_id])
    @all_messages = Message.where(from: [@user.id, @to_user.id], to: [@user.id, @to_user.id])

    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    @message.save
    redirect_to "/messages/#{params[:message][:to]}"
    
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:message, :from, :to)
    end
end

app/controllers/punches_controller.rb
class PunchesController < ApplicationController
  before_action :validate_session, only: [:index]

  def index
    @user = User.find(session[:user_id])
    @punches = Punch.where("user_punched = ?", @user.id )
  end  


  def punch_back
    punch = Punch.find(params[:id])
    if !punch 
      redirect_to root_path
    else
      punch.update(punched_back: true)
      if punch.save
        redirect_to punches_path
      else
        redirect_to punches_path
      end
    end

  end

  private
  def validate_session
    if !session[:user_id]
      redirect_to root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    if session[:user_id]
      user = User.find(session[:user_id])
      redirect_to user_path(user)
    end
    @user = User.new
  end

  def login
    @user = User.find_by(email: params[:session][:email].downcase)
    pass = params[:session][:password]
    if @user.authenticate(pass)
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:danger] = 'Oops... try again'
      render 'new'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [ :show ]

  def new
    @user = User.new
  end

  def create
    @user = User.new( user_params )
    if @user.save
      flash[:success] = 'Succesfully registered'
      redirect_to user_path( @user )
    else
      render 'new'
    end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def grab_profile_picture(user_id)
  end

end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/punches_helper.rb
module PunchesHelper

  def get_user_by_id(user_id)
    User.find(user_id)
  end

  

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<h1>Landing page</h1>

app/views/interests/create.html.erb
<h1>Interests#create</h1>
<p>Find me in app/views/interests/create.html.erb</p>

app/views/interests/destroy.html.erb
<h1>Interests#destroy</h1>
<p>Find me in app/views/interests/destroy.html.erb</p>

app/views/interests/edit.html.erb
<h1>Interests#edit</h1>
<p>Find me in app/views/interests/edit.html.erb</p>

app/views/interests/new.html.erb
<h1>Interests#new</h1>
<p>New Interest</p>

<%= form_for @interest, url: {action: "create"} do |f| %>
  <%= f.text_field :name %>
  <%= f.hidden_field :user_id, :value => @user.id %>
  <%= f.submit "Create" %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverted">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to('logout', logout_path, method: :post) if session[:user_id] %>
          <%= link_to('login', login_path) if !session[:user_id] %>  
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nextnet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- NAVIGATION -->
<%= render 'layouts/navigation' %>

<%= yield %>

<!-- DEBUG -->
<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table>
    <thead>
      <tr>
        <th>From</th>
        <th>Message</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @all_messages.each do |message| %>
        <tr>
          <td><%= User.find_by(id: message.from).name %></td>
          <td><%= message.message %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <%= f.hidden_field :from, value: @user.id %>
  <%= f.hidden_field :to, value: params[:to_id] %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>From</th>
      <th>To</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |user_from| %>
      <tr>
        <td><%= user_from.name %></td>
        <td><%= link_to 'Show conversation', "/messages/#{user_from.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @message.message %>
</p>

<p>
  <strong>From:</strong>
  <%= @message.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @message.to %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/punches/index.html.erb
<h1>
  These person just punched you
</h1>

<% @punches.each do |p| puncher = get_user_by_id(p.user_id) %>
  
  <div class="col-xs-12 well">
      
    <table class="table">
      <tr>
        <td>
          <%= puncher.name %>
        </td>
        <td>
          <%= link_to 'Punch back' %>
        </td>
      </tr>
    </table>

  </div>

<% end %>

app/views/users/new.html.erb
<h1>
  Signup
</h1>

<div class="row">
  
  <%= form_for @user do |usr| %>
    
    <%= usr.label :name %>: <%= usr.text_field :name %><br>
    <%= usr.label :email %>: <%= usr.email_field :email %><br>
    <%= usr.label :password %>: <%= usr.password_field :password %><br>
    <%= usr.label :password_confirmation %>: <%= usr.password_field :password_confirmation %><br>
    <%= usr.submit 'Signup' %>

  <% end %>

</div>

app/views/users/show.html.erb
<h1>User: <%= @user.name %></h1>
<p>User interests:</p>

<ul>
  <% @user.interests.each do |interest| %>
    <li>
      <%= interest.name %>, <%= link_to 'Edit', controller: 'interests', action: 'edit' if @user.id == session[:user_id] %>
    </li>
  <% end %>
</ul>


<% if @user.id == session[:user_id] %>
  <%= link_to 'Add Interest', controller: 'interests', action: 'new' %>
<% end %>
<%= link_to 'Send message', controller: 'messages', action: 'index' %>